### ISSUE TITLE
About the Data Set

### ISSUE THREAD

**Issue by PIANOMAN1223** [J-Cuadrado/OF_EV_SNN#6]
Sorry for the newbie question, but which dataset should I download for DSEC?
train_events.zip (125 GB)
train_images.zip (216 GB)
train_disparity.zip (12 GB)
train_optical_flow.zip (3.7 GB)
train_semantic_segmentation.zip (88.6 MB)
train_calibration.zip

**Comment by J-Cuadrado** [comment]
Hello! You will need the "events" and the "optical_flow" .zip files

**Comment by PIANOMAN1223** [comment]
Thank you very much for your help!
