### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by HYi0** [J-Cuadrado/OF_EV_SNN#7]
Hi, thank you for exposing the code. Can you provide the pretrained models of OF_EV_SNN?

**Comment by J-Cuadrado** [comment]
Hello! There was already an example pretrained model in the "examples" directory. However, I have just added the models we published in our Frontiers paper, both for the MVSEC and for the DSEC dataset. They can all be found in the "examples" folder.

**Comment by HYi0** [comment]
Thank you very much for your response and sharing!
