### ISSUE TITLE
about processing DSEC/test

### ISSUE THREAD

**Issue by HYi0** [J-Cuadrado/OF_EV_SNN#8]
Hi! I have dealt with train dataset of DSEC for training using dsec_dataset_lite/main.py, but there is no code for dealing with test dataset of DSEC. Can you provide the code?

**Comment by J-Cuadrado** [comment]
I have added _file\_generator\_test.py_ in the dsec_dataset_lite/data folder, you simply need to modify the appropriate line in _main.py_ and download the test files in the appropriate folder to run it

**Comment by HYi0** [comment]
Thanks  for sharing the code. But when I run the  file_generator_test.py, I found that there was no "sequence.csv" files, I checked it in the official website of DSEC Dataset and they didn't provide .csv files. can you provide the code or chare the files?

**Comment by HYi0** [comment]
Thank you so much!
